export const RESERVED_SLUGS = [
  "admin",
  "api",
  "auth",
  "login",
  "signup",
  "signout",
  "logout",
  "dashboard",
  "overview",
  "vendor",
  "vendors",
  "settings",
  "shopwus",
  "shopify",
  "profile",
  "invoices",
  "invoice",
  "expenses",
  "customers",
  "leads",
  "analytics",
  "valuation",
  "valuation-calculator",
  "broadcasts",
  "feedback",
  "pricing",
  "terms",
  "privacy",
  "help",
  "support",
  "explore",
  "blog",
  "posts",
  "studio",
  "studios",
  "shop",
  "shops",
  "status",
  "health",
  "webhooks",
  "public",
  "assets",
  "static",
  "favicon",
  "sitemap",
  "robots",
] as const;

export function isReservedSlug(slug: string): boolean {
  const normalized = (slug || "").toLowerCase().trim();
  return (RESERVED_SLUGS as readonly string[]).includes(normalized);
}
